replicaCount: 1

image:
  repository: sprint2-go-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  targetPort: 3000
  nodePort: 30080

resources:
  requests:
    cpu: 50m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

config:
  APP_ENV: "development"
  APP_NAME: "sprint2-go-app"
  LOG_LEVEL: "debug"
  