apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint2-go-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sprint2-go-app
  template:
    metadata:
      labels:
        app: sprint2-go-app
    spec:
      containers:
        - name: sprint2-go-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: sprint2-config
            - secretRef:
                name: sprint2-secret

          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false